/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cityu.ces.gui;

import java.awt.CardLayout;

/**
 *
 * @author Timmy
 */
public class ContactEditorUI extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public ContactEditorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Student = new javax.swing.JButton();
        btn_Course = new javax.swing.JButton();
        btn_Department = new javax.swing.JButton();
        btn_Searchinfo = new javax.swing.JButton();
        lbl_systemname = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btn_Student.setBackground(new java.awt.Color(0, 153, 204));
        btn_Student.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Student.setForeground(new java.awt.Color(255, 255, 255));
        btn_Student.setText("Student");
        btn_Student.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 204, 204), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Student.setName("btn_Student"); // NOI18N
        btn_Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_StudentMouseClicked(evt);
            }
        });

        btn_Course.setBackground(new java.awt.Color(0, 153, 204));
        btn_Course.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Course.setForeground(new java.awt.Color(255, 255, 255));
        btn_Course.setText("Course");
        btn_Course.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 204, 204), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Course.setName("btn_Course"); // NOI18N
        btn_Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CourseMouseClicked(evt);
            }
        });

        btn_Department.setBackground(new java.awt.Color(0, 153, 204));
        btn_Department.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Department.setForeground(new java.awt.Color(255, 255, 255));
        btn_Department.setText("Department");
        btn_Department.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 153, 153), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Department.setName("Department"); // NOI18N
        btn_Department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DepartmentMouseClicked(evt);
            }
        });

        btn_Searchinfo.setBackground(new java.awt.Color(0, 153, 204));
        btn_Searchinfo.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Searchinfo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Searchinfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 153, 153), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Searchinfo.setLabel("Search info");
        btn_Searchinfo.setName("btn_Searchinfo"); // NOI18N
        btn_Searchinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SearchinfoMouseClicked(evt);
            }
        });

        lbl_systemname.setFont(new java.awt.Font("STCaiyun", 1, 48)); // NOI18N
        lbl_systemname.setForeground(new java.awt.Color(255, 0, 0));
        lbl_systemname.setText("Course Enrol SYSTEM");
        lbl_systemname.setName("lbl_systemname"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_Searchinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_systemname)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_systemname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Searchinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_StudentMouseClicked
        // TODO add your handling code here:
        mainPanel.add(new Student_Panel(),"student_panel");
    }//GEN-LAST:event_btn_StudentMouseClicked

    private void btn_CourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CourseMouseClicked
        // TODO add your handling code here:
        mainPanel.add(new Course_Panel(),"course_panel");
    }//GEN-LAST:event_btn_CourseMouseClicked

    private void btn_DepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DepartmentMouseClicked
        // TODO add your handling code here:
        mainPanel.add(new Department_Panel(),"department_panel");
    }//GEN-LAST:event_btn_DepartmentMouseClicked

    private void btn_SearchinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SearchinfoMouseClicked
        // TODO add your handling code here:
        mainPanel.add(new Search_Panel(),"search_panel");
    }//GEN-LAST:event_btn_SearchinfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Course;
    private javax.swing.JButton btn_Department;
    private javax.swing.JButton btn_Searchinfo;
    private javax.swing.JButton btn_Student;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_systemname;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
