/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cityu.ces.gui;

/**
 *
 * @author Timmy
 */
public class Search_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Search
     */
    public Search_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_searchstdname = new javax.swing.JLabel();
        lbl_searchstdid = new javax.swing.JLabel();
        lbl_searchcourse = new javax.swing.JLabel();
        lbl_searchdeptid = new javax.swing.JLabel();
        lbl_searchyear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listinfo = new javax.swing.JList<>();
        btn_search = new javax.swing.JButton();
        lbl_searchpop = new javax.swing.JLabel();
        btn_list = new javax.swing.JButton();
        cbox_searchdeptid = new javax.swing.JComboBox<>();
        cbox_searchcourse = new javax.swing.JComboBox<>();
        rbtn_searchpop = new javax.swing.JRadioButton();
        txt_searchstdname = new javax.swing.JTextField();
        txt_searchstdid = new javax.swing.JTextField();
        cbox_searchyear = new javax.swing.JComboBox<>();

        setMaximumSize(null);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 480));

        lbl_searchstdname.setText("Student name:");
        lbl_searchstdname.setName("lbl_searchstdname"); // NOI18N

        lbl_searchstdid.setText("Student ID:");
        lbl_searchstdid.setName("lbl_searchstdid"); // NOI18N

        lbl_searchcourse.setText("Course Title:");
        lbl_searchcourse.setName("lbl_searchcourse"); // NOI18N

        lbl_searchdeptid.setText("Department ID:");
        lbl_searchdeptid.setName("lbl_searchdeptid"); // NOI18N

        lbl_searchyear.setText("Year:");
        lbl_searchyear.setName("lbl_searchyear"); // NOI18N

        listinfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listinfo.setName("listinfo"); // NOI18N
        jScrollPane1.setViewportView(listinfo);

        btn_search.setText("Search");
        btn_search.setName("btn_search"); // NOI18N

        lbl_searchpop.setText("Popular:");
        lbl_searchpop.setName("lbl_searchpop"); // NOI18N

        btn_list.setText("List");
        btn_list.setName("btn_list"); // NOI18N

        cbox_searchdeptid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_searchdeptid.setName("cbox_searchdeptid"); // NOI18N

        cbox_searchcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_searchcourse.setName("cbox_searchcourse"); // NOI18N

        rbtn_searchpop.setText("jRadioButton1");
        rbtn_searchpop.setName("rbtn_searchpop"); // NOI18N

        txt_searchstdname.setName("txt_searchstdname"); // NOI18N

        txt_searchstdid.setName("txt_searchstdid"); // NOI18N

        cbox_searchyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018" }));
        cbox_searchyear.setName("cbox_searchyear"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_searchcourse)
                            .addComponent(lbl_searchstdname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_searchcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_searchstdname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_searchdeptid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox_searchdeptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_searchstdid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_searchstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(lbl_searchyear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox_searchyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_list))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_searchpop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtn_searchpop)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_searchstdname)
                    .addComponent(lbl_searchstdid)
                    .addComponent(lbl_searchyear)
                    .addComponent(txt_searchstdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_searchstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_searchyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_searchcourse)
                    .addComponent(lbl_searchdeptid)
                    .addComponent(cbox_searchdeptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_searchcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_searchpop)
                    .addComponent(rbtn_searchpop))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search)
                    .addComponent(btn_list))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_list;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cbox_searchcourse;
    private javax.swing.JComboBox<String> cbox_searchdeptid;
    private javax.swing.JComboBox<String> cbox_searchyear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_searchcourse;
    private javax.swing.JLabel lbl_searchdeptid;
    private javax.swing.JLabel lbl_searchpop;
    private javax.swing.JLabel lbl_searchstdid;
    private javax.swing.JLabel lbl_searchstdname;
    private javax.swing.JLabel lbl_searchyear;
    private javax.swing.JList<String> listinfo;
    private javax.swing.JRadioButton rbtn_searchpop;
    private javax.swing.JTextField txt_searchstdid;
    private javax.swing.JTextField txt_searchstdname;
    // End of variables declaration//GEN-END:variables
}
