/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cityu.ces.gui;

import java.util.Date;

import edu.cityu.ces.manager.CourseEnrollmentManager;
import edu.cityu.ces.domain.Student;
import edu.cityu.ces.ContactEditorUI;
import edu.cityu.ces.SpringMongoConfiguration;
import edu.cityu.ces.dao.StudentRepository;
import edu.cityu.ces.domain.Course;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import edu.cityu.ces.domain.Enrolled;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import edu.cityu.ces.domain.Enrolled;
import java.util.List;
/**
 *
 * @author Timmy
 */
public class Student_Panel extends javax.swing.JPanel {
	
	private CourseEnrollmentManager courseEnrollmentManager;
	
	/**
     * Creates new form Student_Panel
     */
    public Student_Panel() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newstudent_panel = new javax.swing.JPanel();
        lbl_newstudname = new javax.swing.JLabel();
        txt_newstudname = new javax.swing.JTextField();
        lbl_newstud_DOB = new javax.swing.JLabel();
        btn_addstud = new javax.swing.JButton();
        txt_newstud_DOB = new javax.swing.JTextField();
        lbl_studid = new javax.swing.JLabel();
        txt_studid = new javax.swing.JTextField();
        lbl_regcourseid = new javax.swing.JLabel();
        cbox_regcourseid = new javax.swing.JComboBox<>();
        lbl_regyear = new javax.swing.JLabel();
        cbox_regyear = new javax.swing.JComboBox<>();
        lbl_regdate = new javax.swing.JLabel();
        txt_regdate = new javax.swing.JTextField();
        btn_updatstud = new javax.swing.JButton();
        btn_delstud = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        setName("student_panel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 480));

        newstudent_panel.setBackground(new java.awt.Color(255, 204, 204));
        newstudent_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Castellar", 1, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        newstudent_panel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newstudent_panel.setName("newstudent_panel"); // NOI18N

        lbl_newstudname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_newstudname.setText("Name:");
        lbl_newstudname.setName("lbl_newstudname"); // NOI18N

        txt_newstudname.setBackground(new java.awt.Color(204, 255, 204));
        txt_newstudname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_newstudname.setName("txt_newstudname"); // NOI18N

        lbl_newstud_DOB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_newstud_DOB.setText("Date of Birth:");
        lbl_newstud_DOB.setName("lbl_newstud_DOB"); // NOI18N

        btn_addstud.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_addstud.setForeground(new java.awt.Color(0, 204, 204));
        btn_addstud.setText("ADD");
        btn_addstud.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 0), new java.awt.Color(255, 255, 0)));
        btn_addstud.setName("btn_addstud"); // NOI18N
        btn_addstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addstudActionPerformed(evt);
            }
        });

        txt_newstud_DOB.setBackground(new java.awt.Color(204, 255, 204));
        txt_newstud_DOB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_newstud_DOB.setName("txt_newstud_DOB"); // NOI18N

        lbl_studid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_studid.setText("Student ID: ");
        lbl_studid.setName("lbl_studid"); // NOI18N

        txt_studid.setBackground(new java.awt.Color(204, 255, 204));
        txt_studid.setName("txt_studid"); // NOI18N

        lbl_regcourseid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_regcourseid.setText("Course ID:");
        lbl_regcourseid.setName("lbl_regcourseid"); // NOI18N

        cbox_regcourseid.setBackground(new java.awt.Color(204, 255, 204));
        cbox_regcourseid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS101" }));
        cbox_regcourseid.setName("cbox_regcourseid"); // NOI18N
        cbox_regcourseid.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbox_regcourseidComponentAdded(evt);
            }
        });
        cbox_regcourseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_regcourseidActionPerformed(evt);
            }
        });

        lbl_regyear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_regyear.setText("Year:");
        lbl_regyear.setName("lbl_regyear"); // NOI18N

        cbox_regyear.setBackground(new java.awt.Color(204, 255, 204));
        cbox_regyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018" }));
        cbox_regyear.setName("cbox_regyear"); // NOI18N

        lbl_regdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_regdate.setText("Date");
        lbl_regdate.setName("lbl_regdate"); // NOI18N

        txt_regdate.setBackground(new java.awt.Color(204, 255, 204));
        txt_regdate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_regdate.setName("txt_regdate"); // NOI18N

        btn_updatstud.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_updatstud.setForeground(new java.awt.Color(0, 204, 204));
        btn_updatstud.setText("Update");
        btn_updatstud.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, java.awt.Color.yellow));
        btn_updatstud.setName("btn_updatstud"); // NOI18N
        btn_updatstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatstudActionPerformed(evt);
            }
        });

        btn_delstud.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_delstud.setForeground(new java.awt.Color(0, 204, 204));
        btn_delstud.setText("Delete");
        btn_delstud.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, java.awt.Color.yellow));
        btn_delstud.setName("btn_delstud"); // NOI18N
        btn_delstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delstudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newstudent_panelLayout = new javax.swing.GroupLayout(newstudent_panel);
        newstudent_panel.setLayout(newstudent_panelLayout);
        newstudent_panelLayout.setHorizontalGroup(
            newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newstudent_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newstudent_panelLayout.createSequentialGroup()
                        .addComponent(btn_addstud, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_updatstud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delstud, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newstudent_panelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lbl_regyear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newstudent_panelLayout.createSequentialGroup()
                                .addComponent(lbl_newstud_DOB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_newstud_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbox_regyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(newstudent_panelLayout.createSequentialGroup()
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newstudent_panelLayout.createSequentialGroup()
                        .addComponent(lbl_studid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_studid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newstudent_panelLayout.createSequentialGroup()
                            .addComponent(lbl_regdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_regdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newstudent_panelLayout.createSequentialGroup()
                            .addComponent(lbl_regcourseid)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbox_regcourseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(newstudent_panelLayout.createSequentialGroup()
                            .addComponent(lbl_newstudname)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_newstudname, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        newstudent_panelLayout.setVerticalGroup(
            newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newstudent_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_studid)
                    .addComponent(txt_studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_newstud_DOB)
                    .addComponent(txt_newstud_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_newstudname)
                    .addComponent(txt_newstudname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_regcourseid)
                    .addComponent(cbox_regcourseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_regyear)
                    .addComponent(cbox_regyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_regdate)
                    .addComponent(txt_regdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addGroup(newstudent_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addstud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updatstud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delstud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newstudent_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newstudent_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addstudActionPerformed
        // TODO add your handling code here:
        Student student = new Student();
        Enrolled enrolled = new Enrolled();
        student.setStudentID(courseEnrollmentManager.generateNewStudentID());
        student.setStuName(txt_newstudname.getText());
        String dataInString = txt_newstud_DOB.getText();
        System.out.println("DOB string: " + dataInString);
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date dob = formatter.parse(dataInString);
            student.setDob(dob);
        } catch (ParseException ex) {
            Logger.getLogger(Student_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        String courseID = (String)cbox_regcourseid.getSelectedItem();
        String year = (String)cbox_regyear.getSelectedItem();
        enrolled.setCourseID(courseID);
        enrolled.setYear(year);
        String dateinstring = txt_regdate.getText();
        try {
            Date date = formatter.parse(dateinstring);
            enrolled.setEnrollDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Student_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        courseEnrollmentManager.enrollCourse(courseID, year,WIDTH);
        courseEnrollmentManager.addStudent(student);
        
        
    }//GEN-LAST:event_btn_addstudActionPerformed

    private void btn_updatstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatstudActionPerformed
        // TODO add your handling code here:
        Student student = new Student();
        if(courseEnrollmentManager.findStudentByStudentID(WIDTH).equals(txt_studid.getText())) {
                  student.setStuName(txt_newstudname.getText());
        String dataInString = txt_newstud_DOB.getText();
        System.out.println("Student has been updated !");
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date dob = formatter.parse(dataInString);
            student.setDob(dob);
            courseEnrollmentManager.updateStudent(student, student);
        } catch (ParseException ex) {
            Logger.getLogger(Student_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_btn_updatstudActionPerformed

    private void btn_delstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delstudActionPerformed
        // TODO add your handling code here:
        Student student = new Student();
        if(String.valueOf(student.getStudentID()).equals(txt_studid.toString())) {
            txt_studid.remove(this);
        }
        if(student.getStuName()== txt_newstudname.toString()){
            txt_newstudname.remove(this);
        }
    }//GEN-LAST:event_btn_delstudActionPerformed

    private void cbox_regcourseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_regcourseidActionPerformed
        // TODO add your handling code here:
        Course course = new Course();
        String cbox_regcourseid = course.getCourseID();
    }//GEN-LAST:event_cbox_regcourseidActionPerformed

    private void cbox_regcourseidComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbox_regcourseidComponentAdded
        // TODO add your handling code here:
        List<Course> courseList = courseEnrollmentManager.listAllCourses();
        int i = 0;
        for (Course course : courseList) {
            cbox_regcourseid.getItemAt(i);
            i++;
        }
        
    }//GEN-LAST:event_cbox_regcourseidComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addstud;
    private javax.swing.JButton btn_delstud;
    private javax.swing.JButton btn_updatstud;
    private javax.swing.JComboBox<String> cbox_regcourseid;
    private javax.swing.JComboBox<String> cbox_regyear;
    private javax.swing.JLabel lbl_newstud_DOB;
    private javax.swing.JLabel lbl_newstudname;
    private javax.swing.JLabel lbl_regcourseid;
    private javax.swing.JLabel lbl_regdate;
    private javax.swing.JLabel lbl_regyear;
    private javax.swing.JLabel lbl_studid;
    private javax.swing.JPanel newstudent_panel;
    private javax.swing.JTextField txt_newstud_DOB;
    private javax.swing.JTextField txt_newstudname;
    private javax.swing.JTextField txt_regdate;
    private javax.swing.JTextField txt_studid;
    // End of variables declaration//GEN-END:variables
    
    public CourseEnrollmentManager getCourseEnrollmentManager() {
		return courseEnrollmentManager;
	}

	public void setCourseEnrollmentManager(CourseEnrollmentManager courseEnrollmentManager) {
		this.courseEnrollmentManager = courseEnrollmentManager;
	}
}