/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 *
 * @author Timmy
 */
@SpringBootApplication
public class ContactEditorUI extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topbar_panel = new javax.swing.JPanel();
        cityu_icon = new javax.swing.JLabel();
        lbl_account = new javax.swing.JLabel();
        accountbox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        student_panel1 = new javax.swing.JPanel();
        lbl_studentname = new javax.swing.JLabel();
        text_studentname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_crousetitle = new javax.swing.JLabel();
        crousetitle_cbox = new javax.swing.JComboBox<>();
        lbl_crouselv = new javax.swing.JLabel();
        cbox_crouselv = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lbl_crouseyear = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lbl_department = new javax.swing.JLabel();
        cbox_department = new javax.swing.JComboBox<>();
        lbl_deptlocatiion = new javax.swing.JLabel();
        cbox_deptlocation = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_list = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));

        topbar_panel.setBackground(new java.awt.Color(204, 204, 255));
        topbar_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        topbar_panel.setName("topbar_panel"); // NOI18N

        cityu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/image/cityu.png"))); // NOI18N
        cityu_icon.setName("cityu_icon"); // NOI18N

        lbl_account.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbl_account.setText("Account:");
        lbl_account.setName("lbl_account"); // NOI18N

        accountbox.setBackground(new java.awt.Color(204, 204, 255));
        accountbox.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        accountbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose...", "Student", "Admin" }));
        accountbox.setName("accountbox"); // NOI18N
        accountbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topbar_panelLayout = new javax.swing.GroupLayout(topbar_panel);
        topbar_panel.setLayout(topbar_panelLayout);
        topbar_panelLayout.setHorizontalGroup(
            topbar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topbar_panelLayout.createSequentialGroup()
                .addComponent(cityu_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_account)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        topbar_panelLayout.setVerticalGroup(
            topbar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cityu_icon)
            .addGroup(topbar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_account)
                .addComponent(accountbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        student_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 24), new java.awt.Color(255, 51, 0))); // NOI18N
        student_panel1.setName("student_panel1"); // NOI18N

        lbl_studentname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_studentname.setText("Name:");
        lbl_studentname.setName("lbl_studentname"); // NOI18N

        text_studentname.setBackground(new java.awt.Color(255, 204, 204));
        text_studentname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        text_studentname.setName("text_studentname"); // NOI18N

        javax.swing.GroupLayout student_panel1Layout = new javax.swing.GroupLayout(student_panel1);
        student_panel1.setLayout(student_panel1Layout);
        student_panel1Layout.setHorizontalGroup(
            student_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_studentname)
                .addGap(18, 18, 18)
                .addComponent(text_studentname, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        student_panel1Layout.setVerticalGroup(
            student_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_studentname)
                    .addComponent(text_studentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crouse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 24), new java.awt.Color(255, 51, 0))); // NOI18N

        lbl_crousetitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_crousetitle.setText("Title :");
        lbl_crousetitle.setName("lbl_crousetitle"); // NOI18N

        crousetitle_cbox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        crousetitle_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        crousetitle_cbox.setName("crousetitle_cbox"); // NOI18N

        lbl_crouselv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_crouselv.setText("Level :");
        lbl_crouselv.setName("lbl_crouselv"); // NOI18N

        cbox_crouselv.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbox_crouselv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        cbox_crouselv.setName("cbox_crouselv"); // NOI18N

        jList1.setBackground(new java.awt.Color(204, 204, 255));
        jList1.setFont(new java.awt.Font("?��細�?��??", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        lbl_crouseyear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_crouseyear.setText("Year :");
        lbl_crouseyear.setName("lbl_crouseyear"); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017" }));

        lbl_department.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_department.setText("Department :");
        lbl_department.setName("lbl_department"); // NOI18N

        cbox_department.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbox_department.setName("cbox_department"); // NOI18N

        lbl_deptlocatiion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_deptlocatiion.setText("Department_location :");
        lbl_deptlocatiion.setName("lbl_deptlocatiion"); // NOI18N

        cbox_deptlocation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbox_deptlocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_deptlocation.setName("cbox_deptlocation"); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Create");
        jButton1.setName("btn_create"); // NOI18N

        btn_add.setBackground(new java.awt.Color(204, 255, 204));
        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_add.setText("Add");
        btn_add.setName("btn_add"); // NOI18N

        btn_update.setBackground(new java.awt.Color(204, 255, 204));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_update.setText("Update");
        btn_update.setName("btn_update"); // NOI18N

        btn_delete.setBackground(new java.awt.Color(204, 255, 204));
        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setName("btn_delete"); // NOI18N

        btn_search.setBackground(new java.awt.Color(204, 255, 204));
        btn_search.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_search.setText("Search");
        btn_search.setName("btn_search"); // NOI18N

        btn_list.setBackground(new java.awt.Color(204, 255, 204));
        btn_list.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_list.setText("List");
        btn_list.setName("btn_list"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_crousetitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(crousetitle_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(lbl_crouselv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbox_crouselv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(lbl_crouseyear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_department)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(lbl_deptlocatiion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbox_deptlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_crousetitle)
                    .addComponent(crousetitle_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_crouselv)
                    .addComponent(cbox_crouselv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_crouseyear)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_department)
                    .addComponent(cbox_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_deptlocatiion)
                    .addComponent(cbox_deptlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)
                        .addComponent(btn_add)
                        .addGap(56, 56, 56)
                        .addComponent(btn_update)
                        .addGap(57, 57, 57)
                        .addComponent(btn_delete)
                        .addGap(58, 58, 58)
                        .addComponent(btn_search)
                        .addGap(59, 59, 59)
                        .addComponent(btn_list)
                        .addGap(0, 246, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(student_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(student_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topbar_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topbar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountbox;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_list;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbox_crouselv;
    private javax.swing.JComboBox<String> cbox_department;
    private javax.swing.JComboBox<String> cbox_deptlocation;
    private javax.swing.JLabel cityu_icon;
    private javax.swing.JComboBox<String> crousetitle_cbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_crouselv;
    private javax.swing.JLabel lbl_crousetitle;
    private javax.swing.JLabel lbl_crouseyear;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_deptlocatiion;
    private javax.swing.JLabel lbl_studentname;
    private javax.swing.JPanel student_panel1;
    private javax.swing.JTextField text_studentname;
    private javax.swing.JPanel topbar_panel;
    // End of variables declaration//GEN-END:variables
}
