/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cityu.ces;

import java.awt.CardLayout;
import java.awt.EventQueue;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

import edu.cityu.ces.gui.Course_Panel;
import edu.cityu.ces.gui.Department_Panel;
import edu.cityu.ces.gui.Search_Panel;
import edu.cityu.ces.gui.Student_Panel;
import edu.cityu.ces.manager.CourseEnrollmentManager;

/**
 *
 * @author Timmy
 */
@SpringBootApplication
public class ContactEditorUI extends javax.swing.JFrame {
	
	@Autowired
	private CourseEnrollmentManager courseEnrollmentManager;

    /**
     * Creates new form MainFrame
     */
    public ContactEditorUI() {
        initComponents(); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_systemname = new javax.swing.JLabel();
        containbtn = new javax.swing.JPanel();
        btn_Student = new javax.swing.JButton("Student");
        btn_Course = new javax.swing.JButton("Course");
        btn_Department = new javax.swing.JButton("Department");
        btn_Searchinfo = new javax.swing.JButton("Search info");
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lbl_systemname.setFont(new java.awt.Font("STCaiyun", 1, 48)); // NOI18N
        lbl_systemname.setForeground(new java.awt.Color(255, 0, 0));
        lbl_systemname.setText("Course Enrol SYSTEM");
        lbl_systemname.setName("lbl_systemname"); // NOI18N

        btn_Student.setBackground(new java.awt.Color(0, 153, 204));
        btn_Student.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Student.setForeground(new java.awt.Color(255, 255, 255));
        btn_Student.setText("Student");
        btn_Student.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 204, 204), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Student.setName("btn_Student"); // NOI18N
        btn_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StudentActionPerformed(evt);
            }
        });

        btn_Course.setBackground(new java.awt.Color(0, 153, 204));
        btn_Course.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Course.setForeground(new java.awt.Color(255, 255, 255));
        btn_Course.setText("Course");
        btn_Course.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 204, 204), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Course.setName("btn_Course"); // NOI18N
        btn_Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CourseActionPerformed(evt);
            }
        });

        btn_Department.setBackground(new java.awt.Color(0, 153, 204));
        btn_Department.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Department.setForeground(new java.awt.Color(255, 255, 255));
        btn_Department.setText("Department");
        btn_Department.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 153, 153), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Department.setName("Department"); // NOI18N
        btn_Department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DepartmentActionPerformed(evt);
            }
        });

        btn_Searchinfo.setBackground(new java.awt.Color(0, 153, 204));
        btn_Searchinfo.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        btn_Searchinfo.setForeground(new java.awt.Color(255, 255, 255));
        btn_Searchinfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, new java.awt.Color(0, 153, 153), java.awt.Color.green, new java.awt.Color(204, 204, 255)));
        btn_Searchinfo.setLabel("Search info");
        btn_Searchinfo.setName("btn_Searchinfo"); // NOI18N
        btn_Searchinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containbtnLayout = new javax.swing.GroupLayout(containbtn);
        containbtn.setLayout(containbtnLayout);
        containbtnLayout.setHorizontalGroup(
            containbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_Searchinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        containbtnLayout.setVerticalGroup(
            containbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containbtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(containbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Searchinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Department, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Course, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_systemname)
                .addGap(110, 110, 110))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(containbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_systemname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StudentActionPerformed
    	Student_Panel student_Panel = new Student_Panel();
    	student_Panel.setCourseEnrollmentManager(courseEnrollmentManager);
    	if (courseEnrollmentManager == null) {
    		System.out.println("courseEnrollmentManager is null!!");
    	}
        mainPanel.removeAll();
        mainPanel.add(student_Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_StudentActionPerformed

    private void btn_CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CourseActionPerformed
    	Course_Panel course_Panel = new Course_Panel();
    	course_Panel.setCourseEnrollmentManager(courseEnrollmentManager);
        mainPanel.removeAll();
        mainPanel.add(course_Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_CourseActionPerformed

    private void btn_DepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DepartmentActionPerformed
    	Department_Panel department_Panel = new Department_Panel();
    	department_Panel.setCourseEnrollmentManager(courseEnrollmentManager);
        mainPanel.removeAll();
        mainPanel.add(department_Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_DepartmentActionPerformed

    private void btn_SearchinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchinfoActionPerformed
    	Search_Panel search_Panel = new Search_Panel();
    	search_Panel.setCourseEnrollmentManager(courseEnrollmentManager);
        mainPanel.removeAll();
        mainPanel.add(search_Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_SearchinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	ConfigurableApplicationContext ctx = new SpringApplicationBuilder(ContactEditorUI.class)
                .headless(false).run(args);

        EventQueue.invokeLater(() -> {
        	ContactEditorUI ex = ctx.getBean(ContactEditorUI.class);
            ex.setVisible(true);
        });

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //new ContactEditorUI();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
        */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Course;
    private javax.swing.JButton btn_Department;
    private javax.swing.JButton btn_Searchinfo;
    private javax.swing.JButton btn_Student;
    private javax.swing.JPanel containbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_systemname;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}